services:
  cassandradatabase:
    image: cassandra:4.0
    environment:
      - CASSANDRA_CLUSTER_NAME=udacity
    volumes:
      - "./sparkifydb_data/data:/var/lib/cassandra:rw"
    ports:
      - "9042:9042"
